import 'model/todo.dart';

final List<Todo> listTodo = [
  Todo(
    maintask: 'Task cha 1',
    //subtask: 'Quét nhà',
    status: false,
    deadline: DateTime(2025, 7, 18, 15, 30),
    creatAt: DateTime(2025, 7, 10, 15, 30),
    priority: Priority.low,
    id: 1,
    category_id: '',
    parent_id: '',
  ),
  Todo(
    maintask: 'Task 1 con cha 1',
    // subtask: 'Làm UI đồ án',
    status: true,
    deadline: DateTime(2025, 7 , 18, 15, 30),
    creatAt: DateTime(2025, 7, 10, 15, 30),
    priority: Priority.high,
    id: 2,
    parent_id: '1',
    category_id: '',
  ),
  Todo(
    maintask: 'Task 2 con cha 1',
    // subtask: 'Dọn bàn',
    status: false,
    deadline: DateTime(2025, 7, 18, 15, 30),
    creatAt: DateTime(2025, 7, 10, 15, 30),
    priority: Priority.nomal,
    id: 3,
    parent_id: '1',
    category_id: '',
  ),
  Todo(
    maintask: 'Task cha 2',
    //subtask: 'Dọn bàn',
    status: true,
    deadline: DateTime(2025, 7, 20, 15, 30),
    creatAt: DateTime(2025, 7, 11, 15, 30),
    priority: Priority.nomal,
    id: 4,
    parent_id: '',
    category_id: '',
  ),
  Todo(
    maintask: 'Task 1 con cha 2',
    // subtask: 'Dọn bàn',
    status: false,
    deadline: DateTime(2025, 7, 20, 15, 30),
    creatAt: DateTime(2025, 7, 1, 15, 30),
    priority: Priority.nomal,
    id: 5,
    parent_id: '4',
    category_id: '',
  ),
  Todo(
    maintask: 'Task 2 con cha 2',
    //subtask: 'Dọn bàn',
    status: true,
    deadline: DateTime(2025, 7, 20, 15, 30),
    creatAt: DateTime(2025, 7, 11, 15, 30),
    priority: Priority.nomal,
    id: 6,
    parent_id: '4',
    category_id: '',
  ),
  Todo(
    maintask: 'Làm việc nhà',
    //subtask: 'Dọn bàn',
    status: true,
    deadline: DateTime.now(),
    creatAt: DateTime.now(),
    priority: Priority.nomal,
    id: 7,
    parent_id: '',
    category_id: '',
  ),
  Todo(
    maintask: 'Làm việc nhà',
    //subtask: 'Dọn bàn',
    status: true,
    deadline: DateTime.now().subtract(Duration(days: 1)),
    creatAt: DateTime.now(),
    priority: Priority.nomal,
    id: 8,
    parent_id: '',
    category_id: '',
  ),
  Todo(
    maintask: 'Làm việc nhà',
    //subtask: 'Dọn bàn',
    status: true,
    deadline: DateTime.now().subtract(Duration(days: 1)),
    creatAt: DateTime.now(),
    priority: Priority.nomal,
    id: 8,
    parent_id: '',
    category_id: '',
  ),
  Todo(
    maintask: 'Làm việc nhà',
    //subtask: 'Dọn bàn',
    status: true,
    deadline: DateTime.now().subtract(Duration(days: 2)),
    creatAt: DateTime.now(),
    priority: Priority.nomal,
    id: 8,
    parent_id: '',
    category_id: '',
  ),
  Todo(
    maintask: 'Làm việc nhà',
    //subtask: 'Dọn bàn',
    status: true,
    deadline: DateTime.now().subtract(Duration(days: 2)),
    creatAt: DateTime.now(),
    priority: Priority.nomal,
    id: 8,
    parent_id: '',
    category_id: '',
  ),
  Todo(
    maintask: 'Làm việc nhà',
    //subtask: 'Dọn bàn',
    status: true,
    deadline: DateTime.now(),
    creatAt: DateTime.now(),
    priority: Priority.nomal,
    id: 8,
    parent_id: '',
    category_id: '',
  ),
  Todo(
    maintask: 'Làm việc nhà',
    //subtask: 'Dọn bàn',
    status: true,
    deadline: DateTime.now(),
    creatAt: DateTime.now(),
    priority: Priority.nomal,
    id: 8,
    parent_id: '',
    category_id: '',
  ),
];
